### ISSUE TITLE
Feature: Feedback and Progress Bar

### ISSUE THREAD

**Issue by TitusSmith33** [GatorEducator/execexam#10]
Description: A UI bar that describes to the user their progress toward their checks.

Expected Behavior: An addition to the UI that puts together a descriptive bar that explains how many checks the student has completed so far-- possibly providing some motivation along the way.

Actual Behavior: There are currenty several boxes that are displayed vertically and as individual boxes. This makes it tough for the students to see how much progress they have made, where a clear bar shows explicit progress.

Proposed Solution: Build a progress bar that shows at the bottom of the output of execexam that shows the student their progress towards their checks.

**Comment by Chezka109** [comment]
We could enhance the UI bar by implementing a color-coded system, such as blue for loading, green for passed checks, and red for failed checks, to represent different stages of progress.

**Comment by gkapfham** [comment]
Hello @TitusSmith33 is there in fact a need for a progress bar in this tool? If not, can you please close this PR?
