### ISSUE TITLE
Bug: Litellm Requires Internet Connection

### ISSUE THREAD

**Issue by suppo01** [GatorEducator/execexam#15]
The Litellm dependency requires the computer to have an internet connection to run. Without an internet connection, the program crashes. A way to fix this could be to write exception handling or something similar to ensure the program is stopped before it reaches this issue, essentially verifying that there is an internet connection.

**Comment by gkapfham** [comment]
Hello @hemanialaparthi can you please give a status update towards your completion of a PR that will resolve this issue?

**Comment by hemanialaparthi** [comment]
Hello @gkapfham! A pull request will be released shortly, and the issue has been resolved. I’ve added exception handling that checks for an internet connection by attempting to connect to Google’s DNS server (8.8.8.8) on port 53, which is a commonly available address. If the connection fails, the program will handle output a message to user early on.
