### ISSUE TITLE
Feature: Add Necessary Markdown Files and Issue Templates

### ISSUE THREAD

**Issue by PCain02** [GatorEducator/execexam#27]
# Feature Request

**Is your feature request related to a problem? Please describe.**
This is related to missing documentation files and templates for when making future issues.

**Describe the solution you'd like**
The solution is adding the proper documentation and adding a way for issue template selection

**Describe alternatives you've considered**
There is no alternative - these documents need added.

**Additional context**
Specific documents to add are `SECURITY.md`, `CONTRIBUTING.md`, `CODE_OF_CONDUCT.md`, and the wiki. The templates need to be selected by the user.

**Comment by gkapfham** [comment]
Hello @PCain02 can you give a status update on the resolution of this issue? Link a PR?

**Comment by PCain02** [comment]
Hello yes this issue should be closed because it was resolved in  https://github.com/GatorEducator/execexam/pull/28 obviously we should continue to update the documentation but this was the start we needed.
