### ISSUE TITLE
Feature: Reset Coder

### ISSUE THREAD

**Issue by Chezka109** [GatorEducator/execexam#29]
Description:
The execexam tool currently lacks any reset functionality for code submissions during exams. This limitation can hinder students who may need to revert to a previous state of their code after making unintended changes or encountering issues during the exam.

Expected Behavior:
There should be reset commands available, such as --hard-reset to reset the entire repository and --reset <filename> to reset specific files. These commands would allow students to easily revert their code to a previous state without manually restoring it, enhancing their ability to manage their submissions effectively.

Actual Behavior:
As it stands, there are no commands available in execexam for resetting code or files. This absence restricts students' ability to recover from mistakes or to start fresh during the exam.

Proposed Solution:

Implement reset commands in execexam:
`--hard-reset`: This command should reset the entire repository to its original state.
`--reset <filename>`: This command should reset the specified file to its last saved state.
Ensure that these commands are user-friendly and provide feedback upon execution, confirming the reset actions to the users.
Adding these reset commands will significantly enhance the functionality of execexam and provide students with better control over their coding environment during exams.

**Comment by Wilor11** [comment]
That's a great proposed solution

**Comment by gkapfham** [comment]
Hello @Chezka109 what is the specific problem that you are aiming to solve that cannot be solved through the use of `git`?

**Comment by Chezka109** [comment]
@gkapfham, I completely understand what you mean. I am now closing this issue.
