### ISSUE TITLE
Feature: Add improvement to the --help function

### ISSUE THREAD

**Issue by hemanialaparthi** [GatorEducator/execexam#30]
It would be beneficial to enhance the `--help` function/ add a new `flag` like the `--help` by including a set of example commands that demonstrate how to effectively use execexam in various scenarios. This feature would provide students with a clearer understanding of how to interact with the tool, improving their overall experience. Having a dedicated flag that outputs a list of useful commands would also be a great addition.

**Comment by gkapfham** [comment]
Can you please explain whether or not this issue is resolved @hemanialaparthi?

**Comment by boulais01** [comment]
@hemanialaparthi If this issue is resolved by the merging of PR #31, please close this issue as resolved.
