### ISSUE TITLE
Automatic Publishing to PyPI Failing.

### ISSUE THREAD

**Issue by boulais01** [GatorEducator/execexam#49]
**Describe the bug**
When the automatic publisher attempts to run, it encounters an existing file error. It would appear that something is misconfigured in the automatic release.

**To Reproduce**
Steps to reproduce the behavior(DO NOT conduct these steps in the main repo):
1. Create a tag
2. Push the tag to origin 

**Expected behavior**
The expected behavior was that upon adding a tag, the project would update on PyPI automatically.

**Screenshots**
![image](https://github.com/user-attachments/assets/46ca1a30-4f70-44ff-97dc-da148ec5dc02)

**Desktop (please complete the following information):**
- N/A (Github Actions)

**Comment by PCain02** [comment]
Execexam 0.3.0 already exists so it needs to be updated to 0.3.1

**Comment by PCain02** [comment]
The current version tagging workflow needs the `pyproject.toml` to also be updated along with the tag or it will not work this can be done manually or with `poetry version 0.3.1` see [Contributing Guidelines](https://github.com/GatorEducator/execexam/wiki/Contributing-Guidelines)
