### ISSUE TITLE
Changelog and Release was not automatically created

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/execexam#57]
After doing a tagged release to GitHub the actual release of the package worked correctly and the system was delivered to PyPI. However, there was no release made available at this site: https://github.com/GatorEducator/execexam/releases.

Are these changelogs/release notes designed to be created automatically or are they done manually? @PCain02 and @boulais01 can you comment on this further?

**Comment by boulais01** [comment]
This is an issue I encountered before and my understanding from my conversation with @PCain02 was that releases had to be done manually in their creation, though I chose to use Github's built-in automatic notes generation for it. PR #61 has now been created to automate this process, and waits only on further review.

**Comment by PCain02** [comment]
Please review https://github.com/GatorEducator/execexam/pull/61 for a fix to this bug.

**Comment by PCain02** [comment]
https://github.com/GatorEducator/execexam/pull/61 was merged so this bug is fixed.
