### ISSUE TITLE
No branch protections

### ISSUE THREAD

**Issue by PCain02** [GatorEducator/execexam#58]
**Describe the bug**
People can push to main without review.

**To Reproduce**
In main:
1. git add .
2. git commit -m ""
3. git push 

**Expected behavior**
No commits to main without review.

**Desktop (please complete the following information):**
ALL

**Comment by boulais01** [comment]
Is the only protection we want the refusal of commits to main without a PR? If there are any other details about the desired outcome, please let me know. I am happy to meet with a students selected as a representative in this and discuss and setup these protections.

**Comment by hannahb09** [comment]
I did this Alish and Kapfhammer and I talked about it in the discord but it is finished and fixed

**Comment by PCain02** [comment]
Perfect then I will close this.
