### ISSUE TITLE
Bug: Advice Model Input

### ISSUE THREAD

**Issue by hemanialaparthi** [GatorEducator/execexam#8]
The program successfully executes even when an invalid model name is provided as an argument for the --advice-model parameter. For example, when running the following command with an incorrect model name, the program doesn't throw an error and proceeds as though the model is valid:

`--advice-model onionrings`

Expected Behavior:
The program should validate the --advice-model argument and return a clear error message when an invalid or unsupported model name is provided, such as:

`Error: The model 'onionrings' is not a valid or supported model name. Please choose a valid model.`

**Comment by gkapfham** [comment]
Hello @hemanialaparthi can you please mark whether or not this issue is resolved by any of the open PRs?

**Comment by boulais01** [comment]
@hemanialaparthi Any updates on this issue?

**Comment by PCain02** [comment]
I think this bug was handled with PR https://github.com/GatorEducator/execexam/pull/22. If this is the case @hemanialaparthi would you mind closing the issue.

**Comment by boulais01** [comment]
@hemanialaparthi can you confirm @PCain02's statement?

**Comment by hemanialaparthi** [comment]
> @hemanialaparthi can you confirm @PCain02's statement?

Yes! @PCain02 is right. This issue has been resolved.
